kind: DaemonSet
apiVersion: apps/v1
metadata: 
 name: nginx-dmn-set
 namespace: nginx
 labels:
   app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-dmn-pod
        image: nginx:latest
        ports:
        - containerPort: 80

